development:
    adapter: postgresql
    database: beehive2_development
    host: localhost
    username: beehive2
    password: gobears
    pool: 5
    timeout: 5000

test:
    adapter: postgresql
    database: beehive2_test
    host: localhost
    username: beehive2
    password: gobears
    pool: 5
    timeout: 5000
